include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = libmtwist

libmtwist_HEADER_FILES = mtwist.h randistrs.h
libmtwist_HEADER_FILES_INSTALL_DIR = mtwist
libmtwist_C_FILES = mtwist.c randistrs.c

include $(GNUSTEP_MAKEFILES)/library.make



